# Generated by Django 3.0.8 on 2020-08-14 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToyNetConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topology', models.TextField(default='<>')),
                ('author_id', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ToyNetSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topology', models.TextField(default='<>')),
                ('user_id', models.IntegerField(blank=True, default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now_add=True)),
                ('toynetconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toynet.ToyNetConfig')),
            ],
        ),
        migrations.CreateModel(
            name='ToyNetSessionOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('toynet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toynet.ToyNetSession')),
            ],
        ),
        migrations.CreateModel(
            name='ToyNetSessionCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField()),
                ('command', models.TextField()),
                ('result', models.TextField(blank=True, default='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('toynet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toynet.ToyNetSession')),
            ],
        ),
    ]
