version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    networks:
      - react_front

  frontend:
    build: https://github.com/Project-Reclass/toynet-react.git#
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - react_front
    environment:
      - SERVER_URI="http://backend:8000"

networks:
  react_front: