# Generated by Django 3.0.8 on 2020-08-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='submodule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
