# Generated by Django 3.0.8 on 2020-08-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submodule_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('module_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submodule_emulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('module_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submodule_lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('module_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Submodule',
            new_name='Curriculum',
        ),
        migrations.AddField(
            model_name='module',
            name='curriculum_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='module_description',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
