# Generated by Django 3.0.8 on 2020-08-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_api', '0002_auto_20200829_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodule_article',
            name='curriculum_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submodule_emulator',
            name='curriculum_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submodule_lesson',
            name='curriculum_id',
            field=models.IntegerField(default=0),
        ),
    ]
